name: Events Tests + Push

on:
    push:
        branches:
        - master
        paths:
        - eventservice/**
        
jobs:
    ci:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Rename pomfile to pom.xml   
              working-directory: ./eventservice  
              run: mv pomfile pom.xml
            - name: Testing with maven   
              working-directory: ./eventservice  
              run: mvn test -q

    cd: 
      runs-on: ubuntu-latest
      needs: ci
      env: 
        IMAGE_TAG: java-events-communication-events-service
      
      steps:
          - uses: actions/checkout@v1
          - name: Docker login
            run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          - name: Build
            working-directory: ./eventservice
            run: docker build -t ${{ env.IMAGE_TAG }} .  
          - name: Tags  
            run: |
              docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
              docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest
          - name: Push
            run: |
              docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
              docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest              